variables:
  system.debug: true
  thisRepo: 'CppBuildTasks-Validation'
  vcpkgGitCommitId: 30124253eecff36bc90f73341edbfb4f845e2a1e

  # vcpkgTriplet: 'x64-windows' Not needed as extracted from the command line arguments.

resources:
  repositories:
  - repository: vcpkg
    type: github
    name: microsoft/vcpkg
    endpoint: vcpkg
    ref: refs/tags/$(vcpkgGitCommitId)

jobs:

- job: vs2019_hosted
  pool:
    name: Hosted Windows 2019 with VS2019

  steps:
    - checkout: self
      submodules: recursive
    - checkout: vcpkg
      displayName: "Checkout vcpkg in '$(Build.SourcesDirectory)/vcpkg'"
    - task: Cache@2
      displayName: Cache vcpkg
      inputs:
        key: $(Build.SourcesDirectory)/$(thisRepo)/cmakeliststxt/vcpkg_x64-windows.txt | "$(vcpkgGitCommitId)" | "$(Agent.OS)"
        path: '$(Build.SourcesDirectory)/vcpkg'
    - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
      displayName: 'Run vcpkg on the submodule without updating'
      inputs:
        # vcpkgTriplet: $(vcpkgTriplet) This is not needed as it is extracted by the response file anyway.
        vcpkgArguments: '@$(Build.SourcesDirectory)/$(thisRepo)/cmakeliststxt/vcpkg_x64-windows.txt'
        vcpkgDirectory: '$(Build.SourcesDirectory)/$(thisRepo)/vcpkg'
        cleanAfterBuild: true
        doNotUpdateVcpkg: true
    - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
      displayName: 'Run vcpkg on the directory (indipendently check-ed out) without updating'
      inputs:
        vcpkgArguments: '@$(Build.SourcesDirectory)/$(thisRepo)/cmakeliststxt/vcpkg_x64-windows.txt'
        vcpkgDirectory: '$(Build.SourcesDirectory)/vcpkg'
        cleanAfterBuild: true
        doNotUpdateVcpkg: true

    - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
      displayName: 'Run CMake with Visual Studio Generator -  Release Configuration'
      inputs:
        cmakeListsTxtPath: '$(thisRepo)/cmakeliststxt/CMakeLists.txt'
        useVcpkgToolchainFile: true
        buildDirectory: '$(Build.ArtifactStagingDirectory)'
        buildWithCMakeArgs: ' --config Release -- /verbosity:detailed'
        cmakeBuildType: Release
        cmakeGenerator: VS16Win64

