jobs:

- job: vs2019_hosted
  pool:
    name: Hosted Windows 2019 with VS2019

  variables:
    system.debug: true
    vcpkgGitCommitId: 0591528cbfde14ccfd3900c3fb19aba382c05349

  steps:
    - task: Cache@2
      displayName: Cache vcpkg
      inputs:
        key: $(Build.SourcesDirectory)/cmakeliststxt/vcpkg_x64-windows.txt | "$(vcpkgGitCommitId)" | "$(Agent.OS)"
        path: '$(Build.BinariesDirectory)/vcpkg'
    - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
      displayName: 'Run vcpkg'
      inputs:
        vcpkgArguments: '@$(Build.SourcesDirectory)/cmakeliststxt/vcpkg_x64-windows.txt'
        vcpkgGitCommitId: $(vcpkgGitCommitId)
        vcpkgGitURL: https://github.com/lukka/vcpkg.git
    - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
      displayName: 'Run CMake with Ninja'
      inputs:
        cmakeListsTxtPath: 'cmakeliststxt/CMakeLists.txt'
        useVcpkgToolchainFile: true
        vcpkgTriplet: '$(RUNVCPKG_VCPKG_TRIPLET)'
        buildWithCMakeArgs: '-- -v'
    - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
      displayName: 'Run CMake with Visual Studio'
      inputs:
        cmakeListsTxtPath: 'cmakeliststxt/CMakeLists.txt'
        useVcpkgToolchainFile: true
        buildDirectory: '$(Build.BinariesDirectory)/vs2019'
        vcpkgTriplet: '$(RUNVCPKG_VCPKG_TRIPLET)'
        buildWithCMakeArgs: '-- -ds'
        cmakeGenerator: VS16Win64

