jobs:

- job: macos_hosted
  pool:
    vmImage: 'macOS-10.14'
    
  variables:
    system.debug: true
    # Since vcpkg is a Git submodule, its commit id is stored at /.git/modules/vcpkg/HEAD.
    # vcpkgGitRef: not needed !

  steps:
    - checkout: self
      submodules: recursive
    - template: ../templates/install-gcc-macos.yml
    - task: CacheBeta@0
      displayName: Cache vcpkg
      inputs:
        key: $(Build.SourcesDirectory)/cmakelists.txt/vcpkg_x64-osx.txt | "$(Agent.OS)" | $(Build.SourcesDirectory)/.git/modules/vcpkg/HEAD | "gcc"
        path: '$(Build.SourcesDirectory)/vcpkg'
    - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
      displayName: 'Run vcpkg'
      inputs:
        vcpkgArguments: '@$(Build.SourcesDirectory)/cmakelists.txt/vcpkg_x64-osx.txt'
        vcpkgDirectory: '$(Build.SourcesDirectory)/vcpkg'
    - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
      displayName: 'Run CMake with Ninja'
      inputs:
        cmakeListsTxtPath: '$(Build.SourcesDirectory)/cmakelists.txt/CMakeLists.txt'
        useVcpkgToolchainFile: true
        buildWithCMakeArgs: '-- -v'