jobs:

- job: ubuntu_hosted
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    system.debug: true
    vcpkgGitRef: 2019.10

  steps:
    - task: Cache@2
      displayName: Cache vcpkg
      inputs:
        key: $(Build.SourcesDirectory)/cmakelists.txt/vcpkg_x64-linux.txt | "$(vcpkgGitRef)" | "$(Agent.OS)"
        path: '$(Build.BinariesDirectory)/vcpkg'
    - task: lucappa.cmake-ninja-vcpkg-tasks-dev.a855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
      displayName: 'Run vcpkg'
      inputs:
        vcpkgArguments: '@$(Build.SourcesDirectory)/cmakelists.txt/vcpkg_x64-linux.txt'
        vcpkgGitCommitId: $(vcpkgGitRef)
        vcpkgGitURL: https://github.com/lukka/vcpkg.git
    - task: lucappa.cmake-ninja-vcpkg-tasks-dev.a2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
      displayName: 'Run CMake with Ninja'
      inputs:
        cmakeListsTxtPath: 'cmakelists.txt/CMakeLists.txt'
        useVcpkgToolchainFile: true
        buildWithCMakeArgs: '-- -v'
        ninjaDownloadUrl: https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip

