jobs:

- job: vs2017_hosted
  pool:
    name: Hosted VS2017

  variables:
    vcpkgPackages: 'sqlite3'
    system.debug: true

  steps:
    - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
      displayName: 'Run vcpkg'
      inputs:
        vcpkgTriplet: 'x64-windows'
        vcpkgArguments: '$(vcpkgPackages)'
    - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
      displayName: 'Run CMake with Ninja'
      inputs:
        cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
        cmakeListsTxtPath: 'cmakelists.txt/CMakeLists.txt'
        useVcpkgToolchainFile: true
        cmakeGenerator: 'Ninja'
        buildDirectory: '$(Build.ArtifactStagingDirectory)'
        vcpkgTriplet: '$(VCPKG_TRIPLET)'
        buildWithCMakeArgs: '-- -v'
