jobs:

- job: vs2017_hosted
  pool:
    name: Hosted VS2017

  variables:
    system.debug: true
    #2019.12
    vcpkgGitRef: 2a0998e5cfada91f19484171f8005eb08b87136b

  steps:
    - task: Cache@2
      displayName: Cache vcpkg
      inputs:
        key: $(Build.SourcesDirectory)/cmakelists.txt/vcpkg_x64-windows.txt | "$(vcpkgGitRef)" | "$(Agent.OS)"
        path: '$(Build.BinariesDirectory)/vcpkg'
    - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
      displayName: 'Run vcpkg'
      inputs:
        vcpkgArguments: '@$(Build.SourcesDirectory)/cmakelists.txt/vcpkg_x64-windows.txt'
        vcpkgGitCommitId: $(vcpkgGitRef)
        vcpkgGitURL: https://github.com/lukka/vcpkg.git
    - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
      displayName: 'Run CMake with Ninja'
      inputs:
        cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
        cmakeListsTxtPath: 'cmakelists.txt/CMakeLists.txt'
        useVcpkgToolchainFile: true
        cmakeGenerator: 'Ninja'
        buildDirectory: '$(Build.ArtifactStagingDirectory)'
        buildWithCMakeArgs: '-- -v'
