jobs:

- job: vs2017_hosted
  pool:
    name: Hosted VS2017

  variables:
    system.debug: true
    # Since vcpkg is a Git submodule, its commit id is stored at /.git/modules/vcpkg/HEAD.
    # vcpkgGitCommitId: not needed !

  steps:
    - checkout: self
      submodules: recursive
    - task: Cache@2
      displayName: Cache vcpkg
      inputs:
        key: $(Build.SourcesDirectory)/cmakelists.txt/vcpkg_x64-windows.txt | $(Build.SourcesDirectory)/.git/modules/vcpkg/HEAD | "$(Agent.OS)"
        path: '$(Build.SourcesDirectory)/vcpkg'
    - task: lucappa.cmake-ninja-vcpkg-tasks-dev.a855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
      displayName: 'Run vcpkg'
      inputs:
        vcpkgArguments: '@$(Build.SourcesDirectory)/cmakelists.txt/vcpkg_x64-windows.txt'
        vcpkgDirectory: '$(Build.SourcesDirectory)/vcpkg'
    - task: lucappa.cmake-ninja-vcpkg-tasks-dev.a2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
      displayName: 'Run CMake with Ninja'
      inputs:
        cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
        cmakeListsTxtPath: 'cmakelists.txt/CMakeLists.txt'
        useVcpkgToolchainFile: true
        buildDirectory: '$(Build.ArtifactStagingDirectory)'
        buildWithCMakeArgs: '-- -v'
