# Copyright (c) 2020-2021-2022 Luca Cappa
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT
name: hosted-matchers
on: [push, workflow_dispatch]

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
            cxx: cl.exe
          - os: ubuntu-latest
            triplet: x64-linux
            cxx: gcc
          - os: macos-latest
            triplet: x64-osx
            cxx: clang

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - uses: ilammy/msvc-dev-cmd@v1

      - uses: lukka/set-shell-env@v1
        with:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cxx }}

      - name: Run CMake+Ninja with triplet (cmd) [CMake error - disabled]
        # This does not work as CMakeLists.txt report relative path to the source dir,
        # that must be the root of repo to work:
        # https://github.com/actions/runner/issues/461
        if: false
        continue-on-error: true
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/matchers/cmake_error/CMakeLists.txt'
          configurePreset: ninja
      - name: Run CMake+Ninja with triplet (cmd) [Build error]
        continue-on-error: true
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/matchers/build_error/CMakeLists.txt'
          configurePreset: ninja
          buildPreset: ninja
      - name: Run CMake+Ninja with triplet (cmd) [CMake error + warning]
        continue-on-error: true
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/cmakepresets/CMakeLists.txt'
          configurePreset: ninja-multi-vcpkg