# Copyright (c) 2019-2020-2021-2022 Luca Cappa
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT

name: hosted-dumplogs-autocache
on: [push, workflow_dispatch]

jobs:

  vcpkg-fails:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            vcpkgCommitId: 'e6509c997fef840f7cfdb84cf6e757b70ee283a8'
          - os: ubuntu-latest
            vcpkgCommitId: 'e6509c997fef840f7cfdb84cf6e757b70ee283a8'
          - os: macos-latest
            vcpkgCommitId: 'e6509c997fef840f7cfdb84cf6e757b70ee283a8'

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: dir
        run: find $RUNNER_WORKSPACE
        shell: bash
      - name: Run vcpkg and dump its failure log
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgGitCommitId: '${{ matrix.vcpkgCommitId }}'
        continue-on-error: true

  cmake-fails:
    name: ${{ matrix.os }}-cmake-log-collection-validation
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
            vcpkgCommitId: '2db6cb97ca925615eeadec71d2ec82b2a9d09e92'
          - os: ubuntu-latest
            triplet: x64-linux
            vcpkgCommitId: '2db6cb97ca925615eeadec71d2ec82b2a9d09e92'
          - os: macos-latest
            triplet: x64-osx
            vcpkgCommitId: '2db6cb97ca925615eeadec71d2ec82b2a9d09e92'
    env:
      VCPKG_URL: https://github.com/lukka/vcpkg.git/

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: lukka/get-cmake@latest
      - name: dir
        run: find $RUNNER_WORKSPACE
        shell: bash
      - name: Restore artifacts for vcpkg (or setup vcpkg if cache miss).
        uses: lukka/run-vcpkg@v10
        id: runvcpkg
        with:
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgGitCommitId: '${{ matrix.vcpkgCommitId }}'
          vcpkgGitURL: '${{ env.VCPKG_URL }}'
      - name: Prints output of run-vcpkg's task
        run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_DEFAULT_TRIPLET_OUT }}' "
      - name: Run CMake and dump its failure log
        continue-on-error: true
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/cmakepresets/CMakeLists.txt'
          configurePreset: ninja-multi-vcpkg
          buildPreset: ninja-multi-vcpkg
      - name: dir
        run: find $RUNNER_WORKSPACE
        shell: bash

