# Copyright (c) 2020-2021-2022 Luca Cappa
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT
#
name: get-cmake-self-hosted-rumner-test
on: [push, workflow_dispatch]

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            vcpkgCommitId: 'c9f906558f9bb12ee9811d6edc98ec9255c6cda5'
          - os: ubuntu-latest
            vcpkgCommitId: 'c9f906558f9bb12ee9811d6edc98ec9255c6cda5'
          - os: macos-latest
            vcpkgCommitId: 'c9f906558f9bb12ee9811d6edc98ec9255c6cda5'

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: lukka/get-cmake@latest
        with:
          useLocalCache: true
          useCloudCache: false
      - name: Dump the content of $RUNNER_TEMP
        run: find $RUNNER_TEMP
        shell: bash
      - name: Dump the content of $RUNNER_WORKSPACE
        run: find $RUNNER_WORKSPACE
        shell: bash
      - uses: lukka/get-cmake@latest
        with:
          useLocalCache: true
          useCloudCache: false
      - name: Dump the content of $RUNNER_TEMP
        run: find $RUNNER_TEMP
        shell: bash
      - name: Dump the content of $RUNNER_WORKSPACE
        run: find $RUNNER_WORKSPACE
        shell: bash
